services:
  frontend:
    image: node:25-alpine
    container_name: portifolio
    working_dir: /app
    volumes:
      - ./portifolio:/app
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0 -p 3000"
    ports:
      - "8050:3000"